### ISSUE TITLE
strain_to_stress

### ISSUE THREAD

**Issue by hvasbath** [tbenthompson/cutde#32]
geometry.strain_to_stress
conversion does not work correctly if the all pairs matrix is being used as input with dimensions higher than 2!
Transposing the matrix to have the strain components as last axis is not enough.

**Comment by tbenthompson** [comment]
I agree that this isn't precisely a "bug", but it would be nice to improve the function or the documentation.

Looking at the code: 
https://github.com/tbenthompson/cutde/blob/3ac6a3e19f70ba50fa87a16d81bec4d96760e273/cutde/geometry.py#L4-L28

the current version assumes that the input shape is (n_tensors, 6). 

Two options here:
1. Just reshape your input before calling: `strain_to_stress(strain_matrix.reshape((-1, 6)), mu, nu).reshape(strain_matrix.shape)`
2. We can modify the function so that it always operates on the last dimension: 
  - `np.sum(strain[..., :3], dim=-1)`
  - use indexing like `strain[..., :3]` and `stress[..., :3]`

In case you haven't seen it before, the elipsis `...` in numpy indexing matches an arbitrary number of axes.

**Comment by hvasbath** [comment]
Thanks for the fast answer! Yes, for now I have been using the first option then. But as to resolve that ambiguity- at least it was my misunderstanding, updating the function would be good. I will make a PR.

**Comment by tbenthompson** [comment]
I made a small update to the README.
